events {}

http {
    server {
        listen 80;

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        location /snippets {
            proxy_pass http://api:8000/snippets;
            proxy_set_header Host $host;
        }
        
        location /docs {
            proxy_pass http://api:8000/docs;
        }
        location /openapi.json {
            proxy_pass http://api:8000/openapi.json;
        }
    }
}