name: CD (Staging & Production)

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🔑 Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 🛠️ Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-fastapi:latest

  deploy-staging:
    needs: build-and-push
    runs-on: [self-hosted, staging]
    steps:
      - name: 🔄 Pull and Restart Staging
        run: |
          cd ~/devops-snippets
          git pull origin main
          docker compose pull
          docker compose up -d

  deploy-production:
    needs: deploy-staging
    runs-on: [self-hosted, production]
    steps:
      - name: 🔄 Pull and Restart Production
        run: |
          cd ~/devops-snippets
          if [ ! -d ".git" ]; then
            git clone https://github.com/Ekzillar/fullstack-deployment-lab.git .
          else
            git pull origin main
          fi
          docker compose pull
          docker compose up -d
          docker image prune -f